### ISSUE TITLE
Syntax error when input has leading/trailing spaces

### ISSUE THREAD

**Issue by randomdude999** [LappySheep/LSCRPL#3]
**Evidence of problem**:
Evaluating " 2" or "2 " causes a syntax error.

**Compiler Version**: 1.2.33

**Extra context or information**:
Full error message:
```
Error found while compiling. Try again.
Traceback (most recent call last):
  File "compiler_1_2.33.py", line 200, in main
    quit()
  File "/usr/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compiler_1_2.33.py", line 219, in <module>
    main()
  File "compiler_1_2.33.py", line 203, in main
    Invalid syntax (Unknown opcode or value?)""")
__main__.compileError: Error found while compiling:
      Invalid syntax (Unknown opcode or value?)
```
This happens because while lscEval uses split() without a separator (which automatically removes leading/trailing whitespace), main() uses split(" ") which returns empty elements with leading/trailing whitespace. Solution: use split() without a separator in main too.

**Comment by LappySheep** [comment]
fixed, thanks for the issue :+1:
